### PR TITLE
Vendoring

### LINKED ISSUE #36: Vendoring dependencies for more reliable upgrades
In order to make dependency upgrade easier to audit, Rooster needs vendored dependencies.

This is probably the right tool for the job: https://github.com/alexcrichton/cargo-vendor

Are you up for the task?

### PR DESCRIPTION
**Pull request by yamnikov-oleg**
All the dependencies are stores in the `vendor` directory.

Except `xcb`. Until the author releases the latest patch (which makes sources generation deterministic to satisfy cargo's checksum test) and until both `x11-clipboard` and `clipboard` crates update their dependency version, `xcb` sources should live in the `patch/rust-xcb` directory, which is just a clone of v0.7.7 with a patch applied. But when `xcb` is updated, this directory and the `[replace]` section in `Cargo.toml` may be removed.

A copy of `xcb` is still present in `vendor/xcb` because cargo for some reason wants to see it there but doesn't use it.

You might probably want to leave a note for contributors to run `cargo-vendor` after updating dependencies :)

Resolves #36

### CODE REVIEW

**Comment by conradkdotcom** [comment]
Thanks a lot @yamnikov-oleg ! I will have a look at that shortly and merge ASAP ! 👍 ❤️

**Comment by conradkdotcom** [comment]
Hey @yamnikov-oleg ! Sorry for taking so long on this PR ! But your awesome work is paying off: just saw that your fix was merged in `xcb`, which means vendoring gets easier for Rooster. Nice ! 👍 

I've removed the patched version of `xcb` and will merge now.

Thanks so much for your help ! 😃

**Comment by conradkdotcom** [comment]
@yamnikov-oleg I'll be updating dependencies now, so we can already see your work actually being useful as we update stuff :) Thanks for making it easier to audit updates. This change was needed so much ! :)

**Comment by conradkdotcom** [comment]
@yamnikov-oleg Woops, made a mistake by thinking xcb was fixed. Your fix was merged but not yet pushed to crates.io : https://github.com/rtbo/rust-xcb/issues/48

**Comment by conradkdotcom** [comment]
@yamnikov-oleg I'm bringing your patch back in Rooster for now and will remove it next time `xcb` is updated on crates.io :)

**Comment by yamnikov-oleg** [comment]
@conradkdotcom I'm glad I've been helpful :)

**Pull request merged**
