### PR TITLE
rust_serialize -> serde 

### PR DESCRIPTION
**Pull request by Eternity-Yarr**
Something like this for #17

### CODE REVIEW

**Comment by conradkdotcom** [comment]
@Eternity-Yarr Wow, thanks so much for taking the time to look at this ! ❤️ 😃 

Just compiled and tested this locally. It seems to work fine on its own. But it is not currently backward compatible with Rooster files from versions `<=2.6.0`, because of the removal of the `Encodable` and `Decodable` traits from `src/safe_string.rs`. We would probably have to rewrite these with serde's [`Serialize`](https://docs.serde.rs/serde/trait.Serialize.html) and [`Deserialize`](https://docs.serde.rs/serde/trait.Deserialize.html) traits.

Would you mind having a look at this please ? If not, that's OK too, just let us know in a comment 😉 

Thanks again !

**Comment by Eternity-Yarr** [comment]
Isn't it derived automagically?

**Comment by conradkdotcom** [comment]
@Eternity-Yarr Yes, I did edit my comment when I realised it missed some useful information. Sorry for any confusion.

**Comment by conradkdotcom** [comment]
@Eternity-Yarr Yes, I did edit my comment when I realised it missed some useful information. Sorry for any confusion. So to answer, `SafeString` is not derived correctly with the attributes `#[...]` since the JSON should not contain `inner`. I hope this clears things up 😃

**Comment by Eternity-Yarr** [comment]
@conradkdotcom well, how about that? :)

**Comment by Eternity-Yarr** [comment]
(forgot to remove `unwrap` call)

**Comment by conradkdotcom** [comment]
Looking good @Eternity-Yarr ! Thanks a lot for working on this so quickly ! I'll give it a go locally and keep you updated in the coming minutes 👍

**Comment by conradkdotcom** [comment]
Seems to work perfectly well ! Thanks a lot @Eternity-Yarr ! And thanks for the unit tests ! ❤️ 

I will publish to Crates.io soon and update the install script soon !

**Pull request merged**
